-- MySQL Script generated by MySQL Workbench
-- 09/09/14 15:40:14
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema instagress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instagress` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `instagress` ;

-- -----------------------------------------------------
-- Table `instagress`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instagress`.`user` (
  `id` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `hash` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `type` INT NULL,
  `expired_date` INT NULL,
  `parent_id` INT NULL DEFAULT 0,
  `status` TINYINT NULL,
  `created` INT NULL,
  `modified` INT NULL,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `full_name` VARCHAR(100) NULL,
  `access_token` VARCHAR(100) NULL,
  `instagram_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instagress`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instagress`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `alias` VARCHAR(100) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_tags_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `instagress`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instagress`.`main_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instagress`.`main_settings` (
  `id` INT NULL AUTO_INCREMENT,
  `activity_speed` TINYINT NULL,
  `media_source` TINYINT NULL,
  `new_media_only` TINYINT NULL,
  `min_likes_filter` INT NULL,
  `max_likes_filter` INT NULL,
  `comment_same_users` TINYINT NULL,
  `unfollow_source` TINYINT NULL,
  `unfollow_not_follow_me` TINYINT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_main_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_main_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `instagress`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instagress`.`auto_stop_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instagress`.`auto_stop_settings` (
  `id` INT NULL AUTO_INCREMENT,
  `likes_counter` INT NULL,
  `comments_counter` INT NULL,
  `follows_counter` INT NULL,
  `unfollows_counter` INT NULL,
  `timer` INT NULL,
  `stop_no_user` TINYINT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auto_stop_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_auto_stop_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `instagress`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instagress`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instagress`.`comments` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `alias` VARCHAR(100) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `instagress`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
