-- MySQL Script generated by MySQL Workbench
-- 09/05/14 16:05:09
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `hash` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `type` INT NULL,
  `expired_date` INT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `alias` VARCHAR(100) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_tags_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`main_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`main_settings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`main_settings` (
  `id` INT NULL AUTO_INCREMENT,
  `activity_speed` TINYINT NULL,
  `media_source` TINYINT NULL,
  `new_media_only` TINYINT NULL,
  `min_likes_filter` INT NULL,
  `max_likes_filter` INT NULL,
  `comment_same_users` TINYINT NULL,
  `unfollow_source` TINYINT NULL,
  `unfollow_not_follow_me` TINYINT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_main_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_main_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auto_stop_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`auto_stop_settings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`auto_stop_settings` (
  `id` INT NULL AUTO_INCREMENT,
  `likes_counter` INT NULL,
  `comments_counter` INT NULL,
  `follows_counter` INT NULL,
  `unfollows_counter` INT NULL,
  `timer` INT NULL,
  `stop_no_user` TINYINT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auto_stop_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_auto_stop_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `alias` VARCHAR(100) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
