-- MySQL Script generated by MySQL Workbench
-- 09/11/14 15:43:42
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- Table  `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `user` (
  `id` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `hash` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `type` INT NULL,
  `expired_date` INT NULL,
  `status` TINYINT NULL,
  `created` INT NULL,
  `modified` INT NULL,
  `full_name` VARCHAR(100) NULL,
  `access_token` VARCHAR(100) NULL,
  `instagram_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `alias` VARCHAR(100) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_tags_users`
    FOREIGN KEY (`users_id`)
    REFERENCES  `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `main_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `main_settings` (
  `id` INT NULL AUTO_INCREMENT,
  `activity_speed` TINYINT NULL,
  `media_source` TINYINT NULL,
  `new_media_only` TINYINT NULL,
  `min_likes_filter` INT NULL,
  `max_likes_filter` INT NULL,
  `comment_same_users` TINYINT NULL,
  `unfollow_source` TINYINT NULL,
  `unfollow_not_follow_me` TINYINT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_main_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_main_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES  `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `auto_stop_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `auto_stop_settings` (
  `id` INT NULL AUTO_INCREMENT,
  `likes_counter` INT NULL,
  `comments_counter` INT NULL,
  `follows_counter` INT NULL,
  `unfollows_counter` INT NULL,
  `timer` INT NULL,
  `stop_no_user` TINYINT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auto_stop_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_auto_stop_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES  `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `comments` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `alias` VARCHAR(100) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES  `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  `user_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `user_child` (
  `id` INT NULL AUTO_INCREMENT,
  `user_child_id` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_child_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_child_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES  `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
